### PR TITLE
initial commit to add neuropil discovery to fluidos  node project

### PR DESCRIPTION
**Pull request by schwicht**
This is our initial commit to add the discovery of fluidos nodes via the neuropil protocol.

### CODE REVIEW

**Comment by fracappa** [comment]
Hi @schwicht, thanks for your contribution!

I kindly ask you to squash your commits before approving and merging as suggested ito our [CONTRIBUTION](https://github.com/fluidos-project/node/blob/main/CONTRIBUTING.md) section.

Moreover, I would like to ask you if you already tested the np procotol into our FLUIDOS Node architecture:

Have you experienced any issue?

Please, feel free to share any feedback.

Thank you!

**Comment by fracappa** [comment]
Hi @schwicht .

Thanks for your feedback

I'm currently asking you to squash your commits so we have a coherent history between the main repo and your fork.
Secondly, I would like to ask if the implementation you provide through this image already works with KnownCluster CRDs.

**Comment by mtt-cc** [comment]
Hello @schwicht, 
by this:
>Currently we change the implementation to use the KnownCluster CRDs. 
do you mean that the current implementation already uses the KnownCluster CRD or that it is a work in progress?
In the second case when do you think the implementation will be available?
Thanks!

**Comment by schwicht** [comment]
I've opened a nes pull request.
The code now uses the KnownCluster CRD and exchanges flavors. In additon, we have added the required kubernetes roles to update these CRDs.

**Pull request closed without merging**
