### PR TITLE
Fixed multi-provider listing in consumer

### PR DESCRIPTION
**Pull request by andreacv98**
Hi everyone,

With this pull request, I want to address a bug found during personal testing of the new installation script.

The bug prevented the installer to set the correct IP addresses of the other providers during the installation of the FLUIDOS Node into the clusters.

I hope, my resolution would be welcomed by you and any feedback would be greatly appreciated.

Best regards,
Andrea

### CODE REVIEW

**Comment by frisso** [comment]
@andreacv98 This looks good to me, thanks!
Please just do a rebase of your code against the master, then we can merge. Thanks!

**Comment by andreacv98** [comment]
> @andreacv98 This looks good to me, thanks! Please just do a rebase of your code against the master, then we can merge. Thanks!

I rebased the branch, now everything should be fine. Thanks for the feedback!

**Comment by fracappa** [comment]
Before closing the PR and merge it I have one final observation:
PRs are suggested to start from local fork `master` (o `main`) branch.

This would help main repo mantainers to keep a clean repo history.

Thanks.
Francesco

**Review by fracappa — APPROVED** [review]

**Pull request merged**
